name: drugdash
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - annotated-doc=0.0.3=pyhcf101f3_1
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - anyio=4.11.0=pyhcf101f3_0
  - aom=3.6.0=h6a678d5_0
  - blas=2.138=openblas
  - blas-devel=3.9.0=38_h1ea3ea9_openblas
  - bottleneck=1.4.2=py312haa0f9ac_1
  - brotli=1.0.9=h166bdaf_7
  - brotli-bin=1.0.9=h166bdaf_7
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cairo=1.18.4=h44eff21_0
  - certifi=2025.10.5=pyhd8ed1ab_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.0=pyh707e725_0
  - contourpy=1.3.1=py312hdb19cb5_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - dav1d=1.2.1=h5eee18b_0
  - dnspython=2.8.0=pyhcf101f3_0
  - email-validator=2.3.0=pyhd8ed1ab_0
  - email_validator=2.3.0=hd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - expat=2.7.1=h6a678d5_0
  - fastapi=0.121.0=h67827d6_0
  - fastapi-cli=0.0.13=pyhcf101f3_0
  - fastapi-core=0.121.0=pyhcf101f3_0
  - fontconfig=2.15.0=h2c49b7f_0
  - fonttools=4.60.1=pyh7db6752_0
  - freetype=2.13.3=h4a9f257_0
  - fribidi=1.0.10=h36c2ea0_0
  - graphite2=1.3.14=h295c915_1
  - greenlet=3.2.4=py312hbdd6827_0
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=10.2.0=hdfddeaa_1
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httptools=0.6.4=py312h5eee18b_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=73.1=h6a678d5_0
  - idna=3.11=pyhd8ed1ab_0
  - jinja2=3.1.6=pyhd8ed1ab_0
  - jpeg=9e=h166bdaf_1
  - kiwisolver=1.4.8=py312h6a678d5_0
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=4.0.0=h6a678d5_0
  - libavif=1.1.1=h5eee18b_0
  - libblas=3.9.0=38_h4a7cf45_openblas
  - libboost=1.88.0=h9d9b81f_0
  - libboost-python=1.88.0=py312hbf651b0_0
  - libbrotlicommon=1.0.9=h166bdaf_7
  - libbrotlidec=1.0.9=h166bdaf_7
  - libbrotlienc=1.0.9=h166bdaf_7
  - libcblas=3.9.0=38_h0358290_openblas
  - libdeflate=1.22=h5eee18b_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=13.2.0=h69a702a_0
  - libgfortran5=13.2.0=ha4646dd_0
  - libglib=2.84.4=h77a78f3_0
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.17=h166bdaf_0
  - liblapack=3.9.0=38_h47877c9_openblas
  - liblapacke=3.9.0=38_h6ae95b6_openblas
  - libnsl=2.0.0=h5eee18b_0
  - libopenblas=0.3.30=h46f56fc_0
  - libopenjpeg=2.5.4=hee96239_1
  - libpng=1.6.50=h2ed474d_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.7.0=hde9077f_0
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.48.0=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.3=pyh7db6752_0
  - matplotlib-base=3.10.6=py312h71dd3da_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncurses=6.5=h7934f7d_0
  - nomkl=3.0=0
  - nodejs>=20.19
  - numexpr=2.14.1=py312ha5a4a6c_0
  - numpy=2.3.4=py312hc213724_0
  - numpy-base=2.3.4=py312hf387b04_0
  - openblas=0.3.30=h5426c36_0
  - openblas-devel=0.3.30=h557178c_0
  - openjpeg=2.5.4=h4e0627c_1
  - openssl=3.0.18=hd6dcaed_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py312h505adc9_0
  - pcre2=10.46=hf426167_0
  - pillow=11.3.0=py312hb1c3d2d_0
  - pip=25.2=pyhc872135_1
  - pixman=0.46.4=h7934f7d_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pydantic=2.12.3=pyh3cfb1c2_0
  - pydantic-core=2.41.4=py312h498d7c9_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - python=3.12.12=hd17a9e1_1
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-dotenv=1.2.1=pyhcf101f3_0
  - python-multipart=0.0.20=pyhff2d567_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=pyh7db6752_0
  - rdkit=2025.03.6=py312h536ce4d_0
  - readline=8.3=hc2a1206_0
  - reportlab=4.4.3=py312h06a4308_0
  - rich=14.2.0=pyhcf101f3_0
  - rich-toolkit=0.15.1=pyhcf101f3_0
  - setuptools=80.9.0=py312h06a4308_0
  - shellingham=1.5.4=pyhd8ed1ab_1
  - scipy
  - six=1.17.0=pyhe01879c_1
  - sniffio=1.3.1=pyhd8ed1ab_1
  - sqlalchemy=2.0.43=py312h7e39e78_0
  - sqlite=3.50.2=hb25bd0a_1
  - starlette=0.49.2=pyhfdc7a7d_0
  - tk=8.6.15=h54e0aa7_0
  - typer=0.20.0=pyhdb1f59b_0
  - typer-slim=0.20.0=pyhcf101f3_0
  - typer-slim-standard=0.20.0=h65a100f_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing-inspection=0.4.2=pyhd8ed1ab_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h04d1e81_0
  - unicodedata2=16.0.0=py312hee96239_0
  - uvicorn=0.38.0=pyh31011fe_0
  - uvicorn-standard=0.38.0=h31011fe_0
  - uvloop=0.22.1=py312h939ff40_1
  - watchfiles=1.1.1=py312h498d7c9_0
  - websockets=15.0.1=py312h5eee18b_0
  - wheel=0.45.1=py312h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7f98852_2
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - cairocffi==1.7.1
      - cairosvg==2.8.2
      - cffi==2.0.0
      - cssselect2==0.8.0
      - defusedxml==0.7.1
      - pycparser==2.23
      - tinycss2==1.4.0
      - webencodings==0.5.1
      - meeko
      - vina
      - gemmi
prefix: /home/luiscamara/miniconda3/envs/dd_dash
